const BASE_URL = "http://172.208.67.125:3000/api"
export const LOGIN_URL = BASE_URL+"/login"
export const ENTER_TRIP_DETAILS_URL = BASE_URL+"/enterTripDetails"
export const GET_DASHBOARD_DETAILS_URL = BASE_URL+"/getDashboardDetails"
export const UPDATE_TRIP_DETAILS_URL = BASE_URL+"/updateTripDetails"